config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  match '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  match '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  match '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  #   # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons
  #
  #   #moved old taxons route to after nested_taxons so nested_taxons will be default route
  #   #this route maybe removed in the near future (no longer used by core)
  #   map.resources :taxons
  #

  namespace :admin do
    resources :adjustments
    resources :zones
    resources :users do
      member do
        post :dismiss_banner
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
          post :update_positions
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end

    resources :option_types do
      collection do
        post :update_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv'
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

app/models/spree/taxonomy.rb
module Spree
  class Taxonomy < ActiveRecord::Base
    validates :name, :presence => true

    has_many :taxons
    has_one :root, :conditions => { :parent_id => nil }, :class_name => 'Spree::Taxon',
                   :dependent => :destroy

    after_save :set_name

    private
      def set_name
        if self.root
          self.root.update_attribute(:name, self.name)
        else
          self.root = Taxon.create!({ :taxonomy_id => self.id, :name => self.name })
        end
      end

  end
end

app/controllers/spree/admin/taxonomies_controller.rb
module Spree
  module Admin
    class TaxonomiesController < ResourceController
      respond_to :json, :only => [:get_children]

      def get_children
        @taxons = Taxon.find(params[:parent_id]).children

        respond_with(@taxons)
      end

      private

      def location_after_save
        if @taxonomy.created_at == @taxonomy.updated_at
          edit_admin_taxonomy_url(@taxonomy)
        else
          admin_taxonomies_url
        end
      end
    end
  end
end

app/views/spree/admin/taxonomies/_form.html.erb
<div data-hook="admin_inside_taxonomy_form">
  <%= f.field_container :name do %>
    <%= f.label :name, t(:name) %> <span class="required">*</span><br />
    <%= error_message_on :taxonomy, :name, :class => 'fullwidth title' %>
    <%= text_field :taxonomy, :name %>
  <% end %>
</div>

app/views/spree/admin/taxonomies/_js_head.html.erb
<% content_for :head do %>
  <%= javascript_tag "var taxonomy_id = #{@taxonomy.id};
    var loading = '#{escape_javascript t(:loading)}';
    var new_taxon = '#{escape_javascript t(:new_taxon)}';
    var server_error = '#{escape_javascript t(:server_error)}';
    var taxonomy_tree_error = '#{escape_javascript t(:taxonomy_tree_error)}';"
  %>
<% end %>

app/views/spree/admin/taxonomies/_list.html.erb
<table class="index" id='listing_taxonomies' data-hook>
  <tr data-hook="taxonomies_header">
    <th><%= t(:name) %></th>
    <th></th>
  </tr>
<% @taxonomies.each do |taxonomy| %>
  <tr id="<%= dom_id taxonomy %>" data-hook="taxonomies_row">
    <td>
      <%= taxonomy.name %>
    </td>
    <td class="actions">
      <%= link_to_edit taxonomy.id, :class => 'edit' %>
      &nbsp;
      <%= link_to_delete taxonomy %>
    </td>
  </tr>
<% end %>
</table>

app/views/spree/admin/taxonomies/_taxon.html.erb
<% if taxon.children.length != 0 %>
  <ul>
    <% taxon.children.each do |child| %>
      <li id="<%= child.id %>" rel="taxon">
        <a style="background-image: url(<%= child.icon.url %>);" href="#"><%= child.name %></a>
        <% if child.children.length > 0 %>
          <%= render :partial => 'taxon', :locals => { :taxon => child } %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/spree/admin/taxonomies/edit.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<%= render :partial => 'js_head' %>

<h1><%= t(:taxonomy_edit) %></h1>

<p id="ajax_error" class="errorExplanation" style="display:none;"></p>

<%= form_for [:admin, @taxonomy] do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
    <div>
      <%= label_tag nil, t(:tree) %><br />
      <div id="taxonomy_tree" class="tree" data-url="<%= admin_taxonomy_taxons_path @taxonomy %>"></div>
    </div>
    <p id="progress" style="display:none;">
      <%= image_tag 'spinner.gif', :title => 'Spinner', :style => "vertical-align:bottom;" %> <%= t(:updating) %>..
    </p>
    <p><br /><small><%= t(:taxonomy_tree_instruction) %></small></p>

    <p class="form-buttons">
      <%= button t(:update) %> <%= t(:or) %> <%= link_to t(:cancel), admin_taxonomies_path %>
    </p>
<% end %>


<% content_for :head do %>
  <%= javascript_tag do -%>
    var initial = [
      { "attr" :
      { "id" : "<%= @taxonomy.root.id %>", "rel" : "root" },
      "data" : "<%= @taxonomy.root.name %>",
      "state" : "open",
      "children" : [
        <% @taxonomy.root.children.each_with_index do |taxon,i| %>
          {
            "attr" :
            { "id" : "<%= taxon.id %>"},
            "data" : "<%= taxon.name %>"
            <% unless taxon.children.empty? %>
              ,"state" : "closed"
            <% end %>
          }<%= ',' if i < (@taxonomy.root.children.size - 1) %>
        <% end %>
      ]
        }
    ];
  <% end -%>
<% end %>

app/views/spree/admin/taxonomies/get_children.json.erb
[<% @taxons.each_with_index do |t,i| %>
  { "attr" :
    { "id" : "<%= t.id %>" },
    "data" : "<%= t.name %>"
    <% unless t.children.empty? %>
      ,"state" : "closed"
    <% end %>
  }<%= "," if i < (@taxons.size - 1) %>
<% end %>]

app/views/spree/admin/taxonomies/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li>
      <%= button_link_to t(:new_taxonomy), new_admin_taxonomy_url, :icon => 'add', :id => 'admin_new_taxonomy_link' %></p>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t(:taxonomies) %></h1>

<div id='list-taxonomies' data-hook>
  <%= render :partial => 'list' %>
</div>

app/views/spree/admin/taxonomies/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t(:new_taxonomy) %></h1>

<%= form_for [:admin, @taxonomy] do |f| %>

  <%= render :partial => 'form', :locals => { :f => f } %>

  <p class="form-buttons" data-hook="buttons">
    <%= button t(:create) %>
  </p>
<% end %>