config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  match '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  match '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  match '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  #   # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons
  #
  #   #moved old taxons route to after nested_taxons so nested_taxons will be default route
  #   #this route maybe removed in the near future (no longer used by core)
  #   map.resources :taxons
  #

  namespace :admin do
    resources :adjustments
    resources :zones
    resources :users do
      member do
        post :dismiss_banner
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
          post :update_positions
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end

    resources :option_types do
      collection do
        post :update_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv'
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

app/models/spree/image.rb
module Spree
  class Image < Asset
    validate :no_attachment_errors
    has_attached_file :attachment,
                      :styles => { :mini => '48x48>', :small => '100x100>', :product => '240x240>', :large => '600x600>' },
                      :default_style => :product,
                      :url => '/spree/products/:id/:style/:basename.:extension',
                      :path => ':rails_root/public/spree/products/:id/:style/:basename.:extension'
    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    # Load user defined paperclip settings
    if Spree::Config[:use_s3]
      s3_creds = { :access_key_id => Spree::Config[:s3_access_key], :secret_access_key => Spree::Config[:s3_secret], :bucket => Spree::Config[:s3_bucket] }
      Spree::Image.attachment_definitions[:attachment][:storage] = :s3
      Spree::Image.attachment_definitions[:attachment][:s3_credentials] = s3_creds
      Spree::Image.attachment_definitions[:attachment][:s3_headers] = ActiveSupport::JSON.decode(Spree::Config[:s3_headers])
      Spree::Image.attachment_definitions[:attachment][:bucket] = Spree::Config[:s3_bucket]
    end

    Spree::Image.attachment_definitions[:attachment][:styles] = ActiveSupport::JSON.decode(Spree::Config[:attachment_styles])
    Spree::Image.attachment_definitions[:attachment][:path] = Spree::Config[:attachment_path]
    Spree::Image.attachment_definitions[:attachment][:default_url] = Spree::Config[:attachment_default_url]
    Spree::Image.attachment_definitions[:attachment][:default_style] = Spree::Config[:attachment_default_style]

    #used by admin products autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interrim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/controllers/spree/admin/images_controller.rb
module Spree
  module Admin
    class ImagesController < ResourceController
      before_filter :load_data

      create.before :set_viewable
      update.before :set_viewable
      destroy.before :destroy_before

      def update_positions
        params[:positions].each do |id, index|
          Image.where(:id => id).update_all(:position => index)
        end

        respond_to do |format|
          format.js  { render :text => 'Ok' }
        end
      end


      private
  
        def location_after_save
          admin_product_images_url(@product)
        end

        def load_data
          @product = Product.find_by_permalink(params[:product_id])
          @variants = @product.variants.collect do |variant|
            [variant.options_text, variant.id]
          end
          @variants.insert(0, [I18n.t(:all), 'All'])
        end

        def set_viewable
          if params[:image].has_key? :viewable_id
            if params[:image][:viewable_id] == 'All'
              @image.viewable = @product.master
            else
              @image.viewable_type = 'Spree::Variant'
              @image.viewable_id = params[:image][:viewable_id]
            end
          else
            @image.viewable = @product.master
          end
        end

        def destroy_before
          @viewable = @image.viewable
        end

    end
  end
end

app/views/spree/admin/images/_form.html.erb
<tr data-hook="file">
  <td><%= t(:filename) %>:</td>
  <td><%= f.file_field :attachment %></td>
</tr>
<% if @product.has_variants? %>
  <tr data-hook="variant">
    <td><%= Spree::Variant.model_name.human %>:</td>
    <td><%= f.select :viewable_id, @variants %></td>
  </tr>
<% else %>
  <%= hidden_field_tag :product_id, @product.id %>
<% end %>
<tr data-hook="alt_text">
  <td><%= t(:alt_text) %>:</td>
  <td><%= f.text_area :alt %></td>
</tr>

app/views/spree/admin/images/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Images' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @image } %>

<%= form_for [:admin, @product, @image], :html => { :multipart => true } do |f| %>
  <table class="basic-table" data-hook="edit_image">
    <tr data-hook="thumbnail">
      <td><%= t(:thumbnail) %>:</td>
      <td><%= link_to image_tag(@image.attachment.url(:mini)), @image.attachment.url(:product) %></td>
    </tr>
    <%= render :partial => 'form', :locals => { :f => f } %>
  </table>
  <p class="form-buttons" data-hook="buttons">
    <%= button t(:update) %>
    <%= t(:or) %> <%= link_to t(:cancel), admin_product_images_url(@product), :id => 'cancel_link' %>
  </p>
<% end %>

app/views/spree/admin/images/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Images'} %>

<table class="index sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_product_images_url(@product) %>">
  <tr data-hook="images_header">
    <th><%= t(:thumbnail) %></th>
    <% if @product.has_variants? %>
      <th><%= Spree::Variant.model_name.human %></th>
    <% end %>
    <th><%= t(:alt_text) %></th>
    <th><%= t(:action) %></th>
  </tr>

  <% @product.images.each do |image| %>
    <tr id="spree_image_<%= image.id %>" data-hook="images_row">
      <td>
        <span class="handle"></span>
        <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:product) %>
      </td>
      <% if @product.has_variants? %>
        <td><%= t(:all) %></td>
      <% end %>
      <td><%= image.alt %></td>
      <td class="actions">
        <%= link_to_with_icon 'edit', t(:edit), edit_admin_product_image_url(@product, image), :class => 'edit' %>
        &nbsp;
        <%= link_to_delete image, { :url => admin_product_image_url(@product, image) }%>
      </td>
    </tr>
  <% end %>

  <% @product.variants.each do |variant| %>
    <% variant.images.each do |image| %>
      <tr id="spree_image_<%= image.id %>" data-hook="images_row">
        <td><span class="handle"></span><%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:product) %></td>
        <% if @product.has_variants? %>
          <td><%= variant.options_text %></td>
        <% end %>
        <td><%= image.alt %></td>
        <td class="actions">
          <%= link_to_with_icon 'edit', t(:edit), edit_admin_product_image_url(@product, image) %>
          &nbsp;
          <%= link_to_delete image, {:url => admin_product_image_url(@product, image) }%>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

<div id="images" data-hook></div>
<br />
<p data-hook="links">
    <%= link_to icon('add') + ' ' + t(:new_image), new_admin_product_image_url(@product), :id => 'new_image_link' %>
</p>

app/views/spree/admin/images/new.html.erb
<h4><%= t(:new_image) %></h4>
<%= form_for [:admin, @product, @image], :html => { :multipart => true } do |f| %>
  <table class="basic-table" data-hook="new_image">
    <%= render :partial => 'form', :locals => { :f => f } %>
  </table>
  <p class="form-buttons" data-hook="buttons">
    <%= button t(:update) %>
    <%= t(:or) %> <%= link_to t(:cancel), admin_product_images_url(@product), :id => 'cancel_link' %>
  </p>
<% end %>

<%= javascript_include_tag 'admin/images/new.js' %>