config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  match '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  match '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  match '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  #   # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons
  #
  #   #moved old taxons route to after nested_taxons so nested_taxons will be default route
  #   #this route maybe removed in the near future (no longer used by core)
  #   map.resources :taxons
  #

  namespace :admin do
    resources :adjustments
    resources :zones
    resources :users do
      member do
        post :dismiss_banner
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
          post :update_positions
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end

    resources :option_types do
      collection do
        post :update_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv'
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

app/controllers/spree/admin/orders/customer_details_controller.rb
module Spree
  module Admin
    module Orders
      class CustomerDetailsController < Spree::Admin::BaseController
        before_filter :load_order

        def show
          edit
          render :action => :edit
        end

        def edit
          @order.build_bill_address(:country_id => Spree::Config[:default_country_id]) if @order.bill_address.nil?
          @order.build_ship_address(:country_id => Spree::Config[:default_country_id]) if @order.ship_address.nil?
        end

        def update
          if @order.update_attributes(params[:order])
            shipping_method = @order.available_shipping_methods(:front_end).first
            if shipping_method
              @order.shipping_method = shipping_method

              if params[:guest_checkout] == 'false' && params[:user_id].present?
                @order.user_id = params[:user_id]
                @order.user true
              end
              @order.save
              @order.create_shipment!
              flash[:notice] = t('customer_details_updated')
              redirect_to edit_admin_order_shipment_path(@order, @order.shipment)
            else
              flash[:error] = t('errors.messages.no_shipping_methods_available')
              redirect_to admin_order_customer_path(@order)
            end
          else
            render :action => :edit
          end

        end

        private

        def load_order
          @order = Order.find_by_number(params[:order_id], :include => :adjustments)
        end

      end
    end
  end
end

app/controllers/spree/admin/orders_controller.rb
module Spree
  module Admin
    class OrdersController < Spree::Admin::BaseController
      require 'spree/core/gateway_error'
      before_filter :initialize_txn_partials
      before_filter :initialize_order_events
      before_filter :load_order, :only => [:show, :edit, :update, :fire, :resend, :history, :user]

      respond_to :html

      def index
        params[:search] ||= {}
        params[:search][:completed_at_is_not_null] ||= '1' if Spree::Config[:show_only_complete_orders_by_default]
        @show_only_completed = params[:search][:completed_at_is_not_null].present?
        params[:search][:meta_sort] ||= @show_only_completed ? 'completed_at.desc' : 'created_at.desc'

        @search = Order.metasearch(params[:search])

        if !params[:search][:created_at_greater_than].blank?
          params[:search][:created_at_greater_than] = Time.zone.parse(params[:search][:created_at_greater_than]).beginning_of_day rescue ""
        end

        if !params[:search][:created_at_less_than].blank?
          params[:search][:created_at_less_than] = Time.zone.parse(params[:search][:created_at_less_than]).end_of_day rescue ""
        end

        if @show_only_completed
          params[:search][:completed_at_greater_than] = params[:search].delete(:created_at_greater_than)
          params[:search][:completed_at_less_than] = params[:search].delete(:created_at_less_than)
        end

        @orders = Order.metasearch(params[:search]).includes([:user, :shipments, :payments]).page(params[:page]).per(Spree::Config[:orders_per_page])
        respond_with(@orders)
      end

      def show
        respond_with(@order)
      end

      def new
        @order = Order.create
        respond_with(@order)
      end

      def edit
        respond_with(@order)
      end

      def update
        return_path = nil
        if @order.update_attributes(params[:order]) && @order.line_items.present?
          @order.update!
          unless @order.complete?

          else
            return_path = admin_order_path(@order)
          end
        else
          @order.errors.add(:line_items, t('errors.messages.blank')) if @order.line_items.empty?
        end

        respond_with(@order) do |format|
          format.html do
            if return_path
              redirect_to return_path
            else
              render :action => :edit
            end
          end
        end
      end


      def fire
        # TODO - possible security check here but right now any admin can before any transition (and the state machine
        # itself will make sure transitions are not applied in the wrong state)
        event = params[:e]
        if @order.send("#{event}")
          flash.notice = t(:order_updated)
        else
          flash[:error] = t(:cannot_perform_operation)
        end
      rescue Spree::Core::GatewayError => ge
        flash[:error] = "#{ge.message}"
      ensure
        respond_with(@order) { |format| format.html { redirect_to :back } }
      end

      def resend
        OrderMailer.confirm_email(@order, true).deliver
        flash.notice = t(:order_email_resent)

        respond_with(@order) { |format| format.html { redirect_to :back } }
      end

      private

      def load_order
        @order ||= Order.find_by_number(params[:id], :include => :adjustments) if params[:id]
        @order
      end

      # Allows extensions to add new forms of payment to provide their own display of transactions
      def initialize_txn_partials
        @txn_partials = []
      end

      # Used for extensions which need to provide their own custom event links on the order details view.
      def initialize_order_events
        @order_events = %w{cancel resume}
      end

    end
  end
end

app/controllers/spree/orders_controller.rb
module Spree
  class OrdersController < BaseController
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/products'

    respond_to :html

    def show
      @order = Order.find_by_number!(params[:id])
      respond_with(@order)
    end

    def update
      @order = current_order
      if @order.update_attributes(params[:order])
        @order.line_items = @order.line_items.select {|li| li.quantity > 0 }
        fire_event('spree.order.contents_changed')
        respond_with(@order) { |format| format.html { redirect_to cart_path } }
      else
        respond_with(@order)
      end
    end

    # Shows the current incomplete order from the session
    def edit
      @order = current_order(true)
    end

    # Adds a new item to the order (creating a new order if none already exists)
    #
    # Parameters can be passed using the following possible parameter configurations:
    #
    # * Single variant/quantity pairing
    # +:variants => {variant_id => quantity}+
    #
    # * Multiple products at once
    # +:products => {product_id => variant_id, product_id => variant_id}, :quantity => quantity +
    # +:products => {product_id => variant_id, product_id => variant_id}}, :quantity => {variant_id => quantity, variant_id => quantity}+
    def populate
      @order = current_order(true)

      params[:products].each do |product_id,variant_id|
        quantity = params[:quantity].to_i if !params[:quantity].is_a?(Hash)
        quantity = params[:quantity][variant_id.to_i].to_i if params[:quantity].is_a?(Hash)
        @order.add_variant(Variant.find(variant_id), quantity) if quantity > 0
      end if params[:products]

      params[:variants].each do |variant_id, quantity|
        quantity = quantity.to_i
        @order.add_variant(Variant.find(variant_id), quantity) if quantity > 0
      end if params[:variants]

      fire_event('spree.cart.add')
      fire_event('spree.order.contents_changed')
      respond_with(@order) { |format| format.html { redirect_to cart_path } }
    end

    def empty
      if @order = current_order
        @order.line_items.destroy_all
      end

      redirect_to spree.cart_path
    end

    def accurate_titles
      @order && @order.completed? ? "#{Order.model_name.human} #{@order.number}" : t(:shopping_cart)
    end
  end
end

app/helpers/spree/admin/orders_helper.rb
module Spree
  module Admin
    module OrdersHelper
      # Renders all the txn partials that may have been specified in the extensions
      def render_txn_partials(order)
        @txn_partials.inject("") do |extras, partial|
          extras += render :partial => partial, :locals => { :payment => order }
        end
      end

      # Renders all the extension partials that may have been specified in the extensions
      def event_links
        links = []
        @order_events.sort.each do |event|
          if @order.send("can_#{event}?")
            links << button_link_to(t(event), fire_admin_order_url(@order, :e => event),
                                    { :method => :put, :confirm => t(:order_sure_want_to, :event => t(event)) })
          end
        end
        links.join('&nbsp;').html_safe
      end
    end
  end
end

app/helpers/spree/orders_helper.rb
module Spree
  module OrdersHelper

  end
end

app/views/spree/admin/orders/_add_product.html.erb
<div id="add-line-item" data-hook>
  <fieldset>
    <legend><%= t(:add_product) %></legend>
    <div style="float:left; width:65%; margin-right:5%;" data-hook="add_product_name">
      <%= label_tag :add_product_name, t(:name_or_sku) %>
      <%= text_field_tag :add_product_name, nil, :class => 'fullwidth title' %>
      <%= hidden_field_tag :add_variant_id %>
    </div>
    <div style="float:left; width:10%; margin-right:5%;" data-hook="add_quantity">
      <%= label_tag :add_quantity, t(:qty) %>
      <%= number_field_tag :add_quantity,  1, :min => 0, :class => 'fullwidth title' %>
    </div>
    <div style="float: left; width: 15%; padding-top: 17px;" data-hook="add_button">
      <%= link_to text_for_button_link(t(:add), :icon => 'add'),
            admin_order_line_items_url(@order),
            {:id => 'add_line_item_to_order', :class => 'button', 'data-update' => 'order-form-wrapper'} %>
    </div>

  </fieldset>
</div>

app/views/spree/admin/orders/_form.html.erb
<% if @line_item.try(:errors).present? %>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @line_item } %>
<% end %>

<%= form_for @order, :url => admin_order_url(@order), :method => :put do |f| %>
  <%= f.hidden_field :number %>
  <table class="index">
    <tbody id="line-items">
      <tr data-hook="admin_order_form_line_items_headers">
        <th><%= t(:item_description) %></th>
        <th class="price"><%= t(:price) %></th>
        <th class="qty"><%= t(:qty) %></th>
        <th class="total"><span><%= t(:total) %></span></th>
        <th class="orders-actions" data-hook="admin_order_form_line_items_header_actions"></th>
      </tr>
      <%= f.fields_for :line_items do |li_form| %>
        <%= render :partial => 'spree/admin/orders/line_item', :locals => { :f => li_form } %>
      <% end %>
    </tbody>
    <tbody id="subtotal" data-hook="admin_order_form_subtotal">
      <tr id="subtotal-row">
        <td colspan="3"><b><%= t(:subtotal) %>:</b></td>
        <td class="total"><span><%= number_to_currency @order.item_total %></span></td>
        <td></td>
      </tr>
    </tbody>
    <tbody id="order-charges" data-hook="admin_order_form_adjustments">
      <% @order.adjustments.each do |adjustment| %>
        <tr>
          <td colspan="3"><strong><%= adjustment.label %></strong></td>
          <td class="total"><span><%= number_to_currency adjustment.amount %></span></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
    <tbody id="order-total" data-hook="admin_order_form_total">
      <tr>
        <td colspan="3"><b><%= t(:order_total) %>:</b></td>
        <td class="total"><span id="order_total"><%= number_to_currency @order.total %></span></td>
        <td></td>
      </tr>
    </tbody>
  </table>

  <p class="form-buttons" data-hook="admin_order_form_buttons">
    <%= button @order.complete? ? t(:update) : t(:continue) %>
    <%= t(:or) %> <%= link_to t(:back), admin_orders_url %>
  </p>

<% end %>

<%= javascript_tag do -%>
  <%= render :partial => 'spree/admin/shared/update_order_state', :handlers => [:js] %>
<% end -%>

app/views/spree/admin/orders/_line_item.html.erb
<tr id="<%= dom_id(f.object) %>" data-hook="admin_order_form_line_item_row">
  <td width="300">
    <%=f.object.variant.product.name%> <%= "(#{f.object.variant.options_text}))" unless f.object.variant.option_values.empty? %>
  </td>
  <td valign="top" class="price"><%= number_to_currency f.object.price %></td>
  <td valign="top" class="qty"><%= f.number_field :quantity, :min => 0, :style => "width:30px;", :class => "qty" %></td>
  <td valign="top" class="total"><%= number_to_currency (f.object.price * f.object.quantity) %></td>
  <td data-hook="admin_order_form_line_item_actions">
    <%= link_to_delete f.object, {:url => admin_order_line_item_url(@order.number, f.object),
                                  :dataType => 'html',
                                  :success => "function(r){ $('#order-form-wrapper').html(r);}"},
                                  :title => "admin_delete_#{dom_id(@order)}" %>
  </td>
</tr>

app/views/spree/admin/orders/edit.html.erb
<%= csrf_meta_tags %>
<div class="order-links" data-hook="admin_order_edit_buttons">
  <div class="toolbar">
    <%= event_links %>
  </div>
  <div class="toolbar">
    <%= button_link_to t(:resend), resend_admin_order_url(@order), :method => :post, :icon => 'send-email' if @order.user %>
  </div>
</div>

<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>

<div data-hook="admin_order_edit_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
</div>

<%= render :partial => 'add_product' %>

<div data-hook="admin_order_edit_form">
  <div id="order-form-wrapper">
    <%= render :partial => 'form', :locals => { :order => @order } %>
  </div>
</div>

<% content_for :head do %>
  <%= javascript_tag 'var expand_variants = true;' %>
<% end %>

app/views/spree/admin/orders/history.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'History' } %>

<h2><%= t(:history) %></h2>

<table class="index">
  <tr data-hook="history_header">
    <th><%= t(:event) %></th>
    <th><%= t(:from_state) %></th>
    <th><%= t(:to_state) %></th>
    <th><%= t(:user) %></th>
    <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
  </tr>
  <% @order.state_changes.sort.each do |event| %>
    <tr data-hook="history_row">
      <td><%=t("#{event.name}") if event.name.present? %></td>
      <td><%=t("#{event.name}_state#{'s' unless event.name == 'order'}.#{event.previous_state}") %></td>
      <td><%=t("#{event.name}_state#{'s' unless event.name == 'order'}.#{event.next_state}") %></td>
      <td><%=event.user.email if event.user %></td>
      <td><%=event.created_at.to_s(:date_time24) %></td>
    </tr>
  <% end %>
  <% if @order.state_changes.empty? %>
    <tr data-hook="history_none">
      <td colspan="5"><%= t(:none_available) %></td>
    </tr>
  <% end %>
</table>

<%= button_link_to t(:continue), admin_orders_url %>

app/views/spree/admin/orders/index.html.erb
<div class='toolbar order-links'>
  <%= button_link_to t(:new_order), new_admin_order_url, :icon => 'add', :id => 'admin_new_order' %>
</div>

<%= render :partial => 'spree/admin/shared/order_sub_menu' %>

<h1><%= t(:listing_orders) %></h1>

<table class="index" id="listing_orders" data-hook>
  <thead>
    <tr data-hook="admin_orders_index_headers">
      <% if @show_only_completed %>
        <th><%= sort_link @search, :completed_at, t(:completed_at, :scope => 'activerecord.attributes.spree/order') %></th>
      <% else %>
        <th><%= sort_link @search, :created_at,   t(:created_at, :scope => 'activerecord.attributes.spree/order') %></th>
      <% end %>
      <th><%= sort_link @search, :number,         t(:number, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :state,          t(:state, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :payment_state,  t(:payment_state, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :shipment_state, t(:shipment_state, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :email,          t(:email, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :total,          t(:total, :scope => 'activerecord.attributes.spree/order') %></th>
      <th data-hook="admin_orders_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr data-hook="admin_orders_index_rows">
      <td><%= l (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
      <td><%= link_to order.number, admin_order_path(order) %></td>
      <td><%= t("order_state.#{order.state.downcase}") %></td>
      <td><%= link_to t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></td>
      <td><%= link_to t("shipment_states.#{order.shipment_state}"), admin_order_shipments_path(order) if order.shipment_state %></td>
      <td><%= order.email %></td>
      <td><%= number_to_currency order.total %></td>
      <td class='actions' data-hook="admin_orders_index_row_actions">
        <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @orders %>


<% content_for :sidebar do %>
  <div class="box" data-hook="admin_orders_index_search">
    <h3><%= t(:search) %></h3>
    <%= form_for [:admin, @search] do |f| %>
      <%= label_tag nil, t(:date_range) %><br />
      <div class="date-range-filter">
        <div class="left sub-field">
          <%= f.text_field :created_at_greater_than, :class => 'datepicker' %><br />
          <%= label_tag nil, t(:start), :class => 'sub' %>
        </div>
        <div class="right sub-field">
          <%= f.text_field :created_at_less_than, :class => 'datepicker' %><br />
          <%= label_tag nil, t(:stop), :class => 'sub' %>
        </div>
      </div>

      <p><%= label_tag nil, t(:status) %><br />
      <%= f.select :state_equals, Spree::Order.state_machines[:state].states.collect {|s| [t("order_state.#{s.name}"), s.value]}, {:include_blank => true} %></p>

      <p>
        <%= label_tag nil, t(:order_number) %><br />
        <%= f.text_field :number_like, :size => 25 %>
      </p>
      <p>
        <%= label_tag nil, t(:email) %><br />
        <%= f.text_field :email_like, :size => 25 %>
      </p>
      <p>
        <%= label_tag nil, t(:first_name_begins_with) %><br />
        <%= f.text_field :bill_address_firstname_starts_with, :size => 25 %>
      </p>
      <p>
        <%= label_tag nil, t(:last_name_begins_with) %><br />
        <%= f.text_field :bill_address_lastname_starts_with, :size => 25 %>
      </p>
      <p>
        <%= f.check_box :completed_at_is_not_null, {:checked => @show_only_completed}, '1', '' %>
        <%= label_tag nil, t(:show_only_complete_orders) %>
      </p>
      <div data-hook="admin_orders_index_search_buttons">
        <p><%= button t(:search) %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/orders/new.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>
<%= csrf_meta_tags %>

<div data-hook="admin_order_new_header">
  <h2><%= t(:new_order) %></h2>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
</div>

<%= render :partial => 'add_product' %>

<div data-hook="admin_order_new_form">
  <div id="order-form-wrapper">
    <%= render :partial => 'form' %>
  </div>
</div>

<% content_for :head do %>
  <%= javascript_tag 'var expand_variants = true;' %>
<% end %>

app/views/spree/admin/orders/show.html.erb
<div class="toolbar order-links" data-hook="admin_order_show_buttons">
  <%= button_link_to t(:cancel), fire_admin_order_url(@order.number, {:e => "cancel"}), :icon => 'delete', :confirm => t(:are_you_sure) if @order.can_cancel? %>
  <%= button_link_to t(:edit), edit_admin_order_url(@order.number), :icon => 'edit' %>
</div>

<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>

<div data-hook="admin_order_show_addresses">
  <% if @order.bill_address %>
    <div class="adr">
      <h4><%= t(:bill_address) %></h4>
      <%= render :partial => 'spree/admin/shared/address', :locals => { :address => @order.bill_address } %>
    </div>
  <% end %>
  <% if @order.ship_address %>
    <div class='adr'>
      <h4><%= t(:ship_address) %></h4>
      <%= render :partial => 'spree/admin/shared/address', :locals => { :address => @order.ship_address } %>
    </div>
    <% end %>
  <hr />
</div>

<div data-hook="admin_order_show_details">
  <%= render :partial => 'spree/admin/shared/order_details', :locals => { :order => @order } %>
</div>