config/routes.rb
Spree::Core::Engine.routes.draw do

  root :to => 'home#index'

  resources :products

  match '/locale/set', :to => 'locale#set'

  resources :tax_categories

  resources :states, :only => :index

  # non-restful checkout stuff
  match '/checkout/update/:state', :to => 'checkout#update', :as => :update_checkout
  match '/checkout/:state', :to => 'checkout#edit', :as => :checkout_state
  match '/checkout', :to => 'checkout#edit', :state => 'address', :as => :checkout

  resources :orders do
    post :populate, :on => :collection

    resources :line_items
    resources :creditcards
    resources :creditcard_payments

    resources :shipments do
      member do
        get :shipping_method
      end
    end

  end
  get '/cart', :to => 'orders#edit', :as => :cart
  put '/cart', :to => 'orders#update', :as => :update_cart
  put '/cart/empty', :to => 'orders#empty', :as => :empty_cart

  resources :shipments do
    member do
      get :shipping_method
      put :shipping_method
    end
  end

  #   # route globbing for pretty nested taxon and product paths
  match '/t/*id', :to => 'taxons#show', :as => :nested_taxons
  #
  #   #moved old taxons route to after nested_taxons so nested_taxons will be default route
  #   #this route maybe removed in the near future (no longer used by core)
  #   map.resources :taxons
  #

  namespace :admin do
    resources :adjustments
    resources :zones
    resources :users do
      member do
        post :dismiss_banner
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories
    resources :configurations, :only => :index
    resources :products do
      resources :product_properties
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
          post :update_positions
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
        end
        collection do
          post :available
          post :batch_select
          get  :selected
        end
      end
    end

    resources :option_types do
      collection do
        post :update_positions
      end
    end

    resources :properties do
      collection do
        get :filtered
      end
    end

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :inventory_settings
    resource :image_settings
    resources :google_analytics

    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end

    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource  :tax_settings
    resources :calculators

    resources :trackers
    resources :payment_methods
    resources :mail_methods do
      member do
        post :testmail
      end
    end
  end

  match '/admin', :to => 'admin/orders#index', :as => :admin

  match '/content/cvv', :to => 'content#cvv'
  match '/content/*path', :to => 'content#show', :via => :get, :as => :content
end

app/models/spree/variant.rb
module Spree
  class Variant < ActiveRecord::Base
    belongs_to :product
    delegate_belongs_to :product, :name, :description, :permalink, :available_on, :tax_category_id, :shipping_category_id, :meta_description, :meta_keywords, :tax_category

    has_many :inventory_units
    has_many :line_items
    has_and_belongs_to_many :option_values, :join_table => 'spree_option_values_variants'
    has_many :images, :as => :viewable, :order => :position, :dependent => :destroy

    validate :check_price
    validates :price, :numericality => { :greater_than_or_equal_to => 0 }, :presence => true
    validates :cost_price, :numericality => { :greater_than_or_equal_to => 0, :allow_nil => true } if self.table_exists? && self.column_names.include?('cost_price')
    validates :count_on_hand, :numericality => true

    before_save :touch_product

    # default variant scope only lists non-deleted variants
    scope :active, where(:deleted_at => nil)
    scope :deleted, where('deleted_at IS NOT NULL')

    # default extra fields for shipping purposes
    @fields = [{ :name => 'Weight', :only => [:variant], :format => '%.2f' },
               { :name => 'Height', :only => [:variant], :format => '%.2f' },
               { :name => 'Width',  :only => [:variant], :format => '%.2f' },
               { :name => 'Depth',  :only => [:variant], :format => '%.2f' }]

    # Returns number of inventory units for this variant (new records haven't been saved to database, yet)
    def on_hand
      Spree::Config[:track_inventory_levels] ? self.count_on_hand : (1.0/0) # Infinity
    end

    # Adjusts the inventory units to match the given new level.
    def on_hand=(new_level)
      if Spree::Config[:track_inventory_levels]
        new_level = new_level.to_i

        # increase Inventory when
        if new_level > on_hand
          # fill backordered orders before creating new units
          inventory_units.with_state('backordered').slice(0, new_level).each do |iu|
            iu.fill_backorder
            new_level -= 1
          end
        end

        self.count_on_hand = new_level
      else
        raise 'Cannot set on_hand value when Spree::Config[:track_inventory_levels] is false'
      end
    end

    # strips all non-price-like characters from the price.
    def price=(price)
      if price.present?
        self[:price] = price.to_s.gsub(/[^0-9\.-]/,'').to_f
      end
    end


    # returns number of units currently on backorder for this variant.
    def on_backorder
      inventory_units.with_state('backordered').size
    end

    # returns true if at least one inventory unit of this variant is "on_hand"
    def in_stock?
      Spree::Config[:track_inventory_levels] ? on_hand > 0 : true
    end
    alias in_stock in_stock?

    def self.additional_fields
      @fields
    end

    def self.additional_fields=(new_fields)
      @fields = new_fields
    end

    # returns true if this variant is allowed to be placed on a new order
    def available?
      Spree::Config[:track_inventory_levels] ? (Spree::Config[:allow_backorders] || self.in_stock?) : true
    end

    def options_text
      self.option_values.sort { |ov1, ov2| ov1.option_type.position <=> ov2.option_type.position }.map { |ov| "#{ov.option_type.presentation}: #{ov.presentation}" }.to_sentence({ :words_connector => ", ", :two_words_connector => ", " })
    end

    def gross_profit
      self.cost_price.nil? ? 0 : (self.price - self.cost_price)
    end

    # use deleted? rather than checking the attribute directly. this
    # allows extensions to override deleted? if they want to provide
    # their own definition.
    def deleted?
      deleted_at
    end

    private
      # Ensures a new variant takes the product master price when price is not supplied
      def check_price
        if self.price.nil?
          raise 'Must supply price for variant or master.price for product.' if self == product.master
          self.price = product.master.price
        end
      end

      def touch_product
        product.touch unless is_master?
      end
  end
end

require_dependency 'spree/variant/scopes'

app/models/spree/variant/scopes.rb
module Spree
  class Variant < ActiveRecord::Base
    #FIXME WARNING tested only under sqlite and postgresql
    scope :descend_by_popularity, order("COALESCE((SELECT COUNT(*) FROM  #{LineItem.quoted_table_name} GROUP BY #{LineItem.quoted_table_name}.variant_id HAVING #{LineItem.quoted_table_name}.variant_id = #{Variant.quoted_table_name}.id), 0) DESC")

    class << self
      # Returns variants that match a given option value
      #
      # Example:
      #
      # product.variants_including_master.has_option(OptionType.find_by_name("shoe-size"),OptionValue.find_by_name("8"))
      def has_option(option_type, *option_values)
        option_types = OptionType.table_name

        option_type_conditions = case option_type
        when OptionType then { "#{option_types}.name" => option_type.name }
        when String     then { "#{option_types}.name" => option_type }
        else                 { "#{option_types}.id"   => option_type }
        end

        relation = joins(:option_values => :option_type).where(option_type_conditions)

        option_values_conditions = option_values.each do |option_value|
          option_value_conditions = case option_value
          when OptionValue then { "#{OptionValue.table_name}.name" => option_value.name }
          when String      then { "#{OptionValue.table_name}.name" => option_value }
          else                  { "#{OptionValue.table_name}.id"   => option_value }
          end
          relation = relation.where(option_value_conditions)
        end

        relation
      end

      alias_method :has_options, :has_option
    end
  end
end

app/controllers/spree/admin/variants_controller.rb
module Spree
  module Admin
    class VariantsController < ResourceController
      belongs_to 'spree/product', :find_by => :permalink
      create.before :create_before
      new_action.before :new_before

      def index
        respond_with(collection) do |format|
          format.html
          format.json { render :json => json_data }
        end
      end

      # override the destory method to set deleted_at value
      # instead of actually deleting the product.
      def destroy
        @variant = Variant.find(params[:id])

        @variant.deleted_at = Time.now()
        if @variant.save
          flash.notice = I18n.t('notice_messages.variant_deleted')
        else
          flash.notice = I18n.t('notice_messages.variant_not_deleted')
        end

        respond_with(@variant) do |format|
          format.html { redirect_to admin_product_variants_url(params[:product_id]) }
          format.js  { render_js_for_destroy }
        end
      end

      def update_positions
        params[:positions].each do |id, index|
          Variant.where(:id => id).update_all(:position => index)
        end

        respond_with(@variant) do |format|
          format.html { redirect_to admin_product_variants_url(params[:product_id]) }
          format.js  { render :text => 'Ok' }
        end
      end

      protected

        def create_before
          option_values = params[:new_variant]
          option_values.each_value {|id| @object.option_values << OptionValue.find(id)}
          @object.save
        end


        def new_before
          @object.attributes = @object.product.master.attributes.except('id', 'created_at', 'deleted_at',
                                                                        'sku', 'is_master', 'count_on_hand')
        end

        def collection
          @deleted = (params.key?(:deleted)  && params[:deleted] == "on") ? "checked" : ""

          if @deleted.blank?
            @collection ||= super
          else
            @collection ||= Variant.where(:product_id => parent.id).deleted
          end
          @collection
        end

        def json_data
          ( parent.variants.presence || [parent.master] ).map do |v|
            { :label => v.options_text.presence || v.name, :id => v.id }
          end
        end

    end
  end
end

app/views/spree/admin/variants/_form.html.erb
<div class="clearfix">
  <div class="left" data-hook="variants">

    <% @product.options.each do |option| %>
      <p data-hook="presentation">
        <%= label :new_variant, option.option_type.presentation %><br />
        <% if @variant.new_record? %>
          <%= select(:new_variant, option.option_type.presentation,
            option.option_type.option_values.collect {|ov| [ ov.presentation, ov.id ] },
            {})
          %>
        <% else %>
          <% opt = @variant.option_values.detect {|o| o.option_type == option.option_type }.presentation %>
          <%= text_field(:new_variant,  option.option_type.presentation, :value => opt, :disabled => 'disabled') %>
        <% end %>
      </p>
    <% end %>

    <p data-hook="sku"><%= f.label :sku, t(:sku) %><br />
    <%= f.text_field :sku %></p>

    <p data-hook="price"><%= f.label :price, t(:price) %>:<br />
    <%= f.text_field :price, :value => number_with_precision(@variant.price, :precision => 2) %></p>

    <p data-hook="cost_price"><%= f.label :cost_price, t(:cost_price) %>:<br />
    <%= f.text_field :cost_price, :value => number_with_precision(@variant.cost_price, :precision => 2) %></p>

    <% if Spree::Config[:track_inventory_levels] %>
      <p data-hook="on_hand"><%= f.label :on_hand, t(:on_hand) %>: <br />
      <%= f.text_field :on_hand %></p>
    <% end %>
  </div>
  <div class="right">

    <% Spree::Variant.additional_fields.select{|af| af[:only].nil? || af[:only].include?(:variant) }.each do |field| %>
      <%= render :partial => 'spree/admin/shared/additional_field', :locals => { :field => field, :f => f } %>
    <% end %>

  </div>
</div>

app/views/spree/admin/variants/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Variants' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <div data-hook="admin_variant_edit_form">
    <%= render :partial => 'form', :locals => { :f => f } %>
  </div>

  <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/variants/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Variants'} %>

<table class="index sortable" data-sortable-link="<%= update_positions_admin_product_variants_path(@product) %>">
  <tr data-hook="variants_header">
    <th><%= t(:options) %></th>
    <th><%= t(:price) %></th>
    <th><%= t(:sku) %></th>
    <% Spree::Variant.additional_fields.select { |f| f[:only].nil? || f[:only].include?(:variant) }.each do |field| %>
      <th><%= t('activerecord.attributes.variant.' + field[:name].downcase, :default => field[:name].titleize) %></th>
    <% end %>
    <th><%= t(:on_hand) %></th>
    <th><%= t(:action) %></th>
  </tr>
  <% @variants.each do |variant| %>
    <!-- you can skip variant with no options: that's just the default variant that all products have -->
    <% next if variant.option_values.empty? %>
    <tr id="spree_variant_<%= variant.id %>" <%= 'style="color:red;"' if variant.deleted? %> data-hook="variants_row">
      <td><span class="handle"></span> <%= variant.options_text %></td>
      <td><%= number_to_currency variant.price %></td>
      <td><%= variant.sku %></td>
      <% Spree::Variant.additional_fields.select { |f| f[:only].nil? || f[:only].include?(:variant) }.each do |field| %>
        <td><%= variant[field[:name].gsub(" ", "_").downcase] %></td>
      <% end %>
      <td><%= variant.on_hand %></td>
      <td valign="top">
        <%= link_to_edit(variant) unless variant.deleted? %>
        &nbsp;
        <%= link_to_delete(variant) unless variant.deleted? %>
      </td>
    </tr>
  <% end %>
  <% unless @product.has_variants? %>
    <tr><td colspan="9"><%= t(:none) %></td></tr>
  <% end %>
</table>

<% if @product.empty_option_values? %>

  <p class='first_add_option_types' data-hook="first_add_option_types">
    <%= t(:to_add_variants_you_must_first_define) %>
    <%= link_to t(:option_types), selected_admin_product_option_types_url(@product) %>
    <%= t(:and) %>
    <%= link_to t(:option_values), admin_option_types_url %>
  </p>

<% else %>

  <div id="new_variant" data-hook></div>

  <br />

  <p id="new_var_link" data-hook>

    <%= link_to icon('add') + ' ' + t(:new_variant), new_admin_product_variant_url(@product), :remote => :true, 'data-update' => 'new_variant', :class => 'iconlink new' %>

    &nbsp;|&nbsp;

    <%= link_to @deleted.blank? ? t(:show_deleted) : t(:show_active), admin_product_variants_url(@product, :deleted => @deleted.blank? ? "on" : "off") %>
  </p>

  <%= image_tag 'spinner.gif', :plugin => 'spree', :style => 'display:none;', :id => 'busy_indicator' %>
<% end %>

app/views/spree/admin/variants/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <fieldset data-hook="admin_variant_new_form">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/variants/new.js.erb
$("#new_variant").html('<%= escape_javascript(render :template => 'spree/admin/variants/new', :formats => [:html], :handlers => [:erb]) %>');
$("#new_var_link").hide();